services:
  api:
    build: .
    ports:
      - 8002:8002
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload

    environment:
      - DATABASE_HOSTNAME=host.docker.internal
      - DATABASE_PORT=55000
      - DATABASE_PASSWORD=postgrespw
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=8e04c1417fa134ac145c23965eae096ff3ced9a0a05619cbdcc53936ecd55d72
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
